# Generated by Django 2.2.13 on 2020-06-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200622_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='jhgjghgjg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='jhjhgjg',
        ),
    ]
