# Generated by Django 2.2.13 on 2020-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20200622_0520"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="dfgsdfgs",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="sdfasfg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
