# Generated by Django 2.2.13 on 2020-06-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20200622_0618"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="dfgsdfgs",),
        migrations.RemoveField(model_name="homepage", name="sdfasfg",),
    ]
