# Generated by Django 2.2.13 on 2020-06-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200622_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hytryuryu',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jytut',
        ),
    ]
